### PR TITLE
Public Interface

### LINKED ISSUE #20: Implement Package/Library Interface (Public API)
Create a public interface based on the private mapped zfs functions.

Attempt to remain close to the existing `go-zfs` API. For reference: https://godoc.org/github.com/mistifyio/go-zfs

### PR DESCRIPTION
**Pull request by TauZero**
Resolves #20

Note: This excludes mount/unmount and receive

[Review on Reviewable](https://reviewable.io/reviews/mistifyio/gozfs/24)

### CODE REVIEW

**Comment by mmlb** [comment]
Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[dataset.go, line 176 \[r1\]](https://reviewable.io:443/reviews/mistifyio/gozfs/24#-KCH3Wqd23TqbACtGwvh:-KCH3Wqd23TqbACtGwvi:1065606302) ([raw file](https://github.com/mistifyio/gozfs/blob/79f4c96b37e939fb70b93b7f659f5d807bda9a7b/dataset.go#L176)):*
why not name it `ds` instead of `in`?

---

*[dataset.go, line 324 \[r1\]](https://reviewable.io:443/reviews/mistifyio/gozfs/24#-KCH4h8RycUVA3B6mAK6:-KCH4h8S7teCeQc5-T_i:-1129320757) ([raw file](https://github.com/mistifyio/gozfs/blob/79f4c96b37e939fb70b93b7f659f5d807bda9a7b/dataset.go#L324)):*
bring the `clones.` up to previous line.

---

*[dataset.go, line 364 \[r1\]](https://reviewable.io:443/reviews/mistifyio/gozfs/24#-KCH5Vnaj26MJ0FYCSn9:-KCH5Vnbt9wDjlNzaEQN:-1245573912) ([raw file](https://github.com/mistifyio/gozfs/blob/79f4c96b37e939fb70b93b7f659f5d807bda9a7b/dataset.go#L364)):*
I think a comment should be made that it's returned by lookup-through-reflection. But I think we should just get rid of this method, the properties are already public so the user can just get at the one it wants, or do the reflection look up themselves.

---

*[dataset.go, line 366 \[r1\]](https://reviewable.io:443/reviews/mistifyio/gozfs/24#-KCH5C0QFJfuVDEL-8gN:-KCH5C0QFJfuVDEL-8gO:1408466106) ([raw file](https://github.com/mistifyio/gozfs/blob/79f4c96b37e939fb70b93b7f659f5d807bda9a7b/dataset.go#L366)):*
bring `dV` down closer to `property :=`.

---

*[dataset.go, line 465 \[r1\]](https://reviewable.io:443/reviews/mistifyio/gozfs/24#-KCH7dKZZyfrnTAEAnOO:-KCH7dKZZyfrnTAEAnOP:-1685930412) ([raw file](https://github.com/mistifyio/gozfs/blob/79f4c96b37e939fb70b93b7f659f5d807bda9a7b/dataset.go#L465)):*
hmm I can't remember why this is here vs `defered`. Shouldn't this be closedr regardless of there being an error or not? Seems this should be:

```
err := send(d.Name, outputFdCloser.Fd(), "", false, false);
if !isFdCloser {
		outputFdCloser.Close()
}
if err != nil {
		return err
}
return <-done
```

---

*[dataset.go, line 500 \[r1\]](https://reviewable.io:443/reviews/mistifyio/gozfs/24#-KCH8r9zjVWOFG1q1HAJ:-KCH8r9zjVWOFG1q1HAK:456540435) ([raw file](https://github.com/mistifyio/gozfs/blob/79f4c96b37e939fb70b93b7f659f5d807bda9a7b/dataset.go#L500)):*
I kind of hate this name, what other kind of pool would we possibly return? I'd rather have `Pool` but meh.

---

*[exists.go, line 28 \[r1\]](https://reviewable.io:443/reviews/mistifyio/gozfs/24#-KCH9C8Mfbt0iSZsLW-u:-KCH9C8Mfbt0iSZsLW-v:-1154994164) ([raw file](https://github.com/mistifyio/gozfs/blob/79f4c96b37e939fb70b93b7f659f5d807bda9a7b/exists.go#L28)):*
why are the strings being compared? `err != syscall.ENOENT` isn't correct?

---

*[logger.go, line 3 \[r1\]](https://reviewable.io:443/reviews/mistifyio/gozfs/24#-KCHCgIP1mgeV8JpOatg:-KCHCgIQUKcgvbvRmOsu:-987198936) ([raw file](https://github.com/mistifyio/gozfs/blob/79f4c96b37e939fb70b93b7f659f5d807bda9a7b/logger.go#L3)):*
thoughts on https://0value.com/about-Go-logging instead

---

*[cmd/gozfs/main.go, line 1 \[r1\]](https://reviewable.io:443/reviews/mistifyio/gozfs/24#-KCH9bT1ncmWFT-Rr68Z:-KCH9bT2H1EQVoyck98H:1563421301) ([raw file](https://github.com/mistifyio/gozfs/blob/79f4c96b37e939fb70b93b7f659f5d807bda9a7b/cmd/gozfs/main.go#L1)):*
My eyes glazed over here, I'll just assume you moved the file over

---

*[cmd/gozfs/main.go, line 92 \[r1\]](https://reviewable.io:443/reviews/mistifyio/gozfs/24#-KCH9pm0ZFZ08AwkE94N:-KCH9pm0ZFZ08AwkE94O:-1813991606) ([raw file](https://github.com/mistifyio/gozfs/blob/79f4c96b37e939fb70b93b7f659f5d807bda9a7b/cmd/gozfs/main.go#L92)):*
`recursive-clones` and `force-unmount` maybe?

---

*[cmd/gozfs/main.go, line 148 \[r1\]](https://reviewable.io:443/reviews/mistifyio/gozfs/24#-KCH9vuGJdfF6DbZ5RYU:-KCH9vuGJdfF6DbZ5RYV:2071370216) ([raw file](https://github.com/mistifyio/gozfs/blob/79f4c96b37e939fb70b93b7f659f5d807bda9a7b/cmd/gozfs/main.go#L148)):*
`destroy-recent`?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/gozfs/24)*

**Comment by TauZero** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[dataset.go, line 324 \[r1\]](https://reviewable.io:443/reviews/mistifyio/gozfs/24#-KCH4h8RycUVA3B6mAK6:-KCHJ5fgM3gicPfGrVab:1466754613) ([raw file](https://github.com/mistifyio/gozfs/blob/79f4c96b37e939fb70b93b7f659f5d807bda9a7b/dataset.go#L324)):*
It was wrapped for an 80 character line.

---

*[dataset.go, line 366 \[r1\]](https://reviewable.io:443/reviews/mistifyio/gozfs/24#-KCH5C0QFJfuVDEL-8gN:-KCHJlg0_GBzi6JjJMRN:-499146009) ([raw file](https://github.com/mistifyio/gozfs/blob/79f4c96b37e939fb70b93b7f659f5d807bda9a7b/dataset.go#L366)):*
Done.

---

*[logger.go, line 3 \[r1\]](https://reviewable.io:443/reviews/mistifyio/gozfs/24#-KCHCgIP1mgeV8JpOatg:-KCHKFsH4Q_HXuRLS5Hn:1110193498) ([raw file](https://github.com/mistifyio/gozfs/blob/79f4c96b37e939fb70b93b7f659f5d807bda9a7b/logger.go#L3)):*
Removing. Wasn't actually used anywhere and `gozfs` is thin enough that just returning errors should be sufficient.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/gozfs/24)*

**Comment by TauZero** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[cmd/gozfs/main.go, line 92 \[r1\]](https://reviewable.io:443/reviews/mistifyio/gozfs/24#-KCH9pm0ZFZ08AwkE94N:-KCHKvcN4cCDvjYdtFId:-499146009) ([raw file](https://github.com/mistifyio/gozfs/blob/79f4c96b37e939fb70b93b7f659f5d807bda9a7b/cmd/gozfs/main.go#L92)):*
Done.

---

*[cmd/gozfs/main.go, line 148 \[r1\]](https://reviewable.io:443/reviews/mistifyio/gozfs/24#-KCH9vuGJdfF6DbZ5RYU:-KCHKwMV7bYHRwCcxJJE:-499146009) ([raw file](https://github.com/mistifyio/gozfs/blob/79f4c96b37e939fb70b93b7f659f5d807bda9a7b/cmd/gozfs/main.go#L148)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/gozfs/24)*

**Comment by TauZero** [comment]
Review status: 15 of 17 files reviewed at latest revision, 10 unresolved discussions.

---

*[dataset.go, line 364 \[r1\]](https://reviewable.io:443/reviews/mistifyio/gozfs/24#-KCH5Vnaj26MJ0FYCSn9:-KCHMWotckkvKZf0t4e6:-251496827) ([raw file](https://github.com/mistifyio/gozfs/blob/79f4c96b37e939fb70b93b7f659f5d807bda9a7b/dataset.go#L364)):*
The `Dataset.ds` is private and the main reason that the `type ds` properties are public is for JSON marshalling/unmarshalling.

---

*[dataset.go, line 500 \[r1\]](https://reviewable.io:443/reviews/mistifyio/gozfs/24#-KCH8r9zjVWOFG1q1HAJ:-KCHPgrBmggHM8mnV9UW:-499146009) ([raw file](https://github.com/mistifyio/gozfs/blob/79f4c96b37e939fb70b93b7f659f5d807bda9a7b/dataset.go#L500)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/gozfs/24)*

**Comment by TauZero** [comment]
Review status: 14 of 17 files reviewed at latest revision, 7 unresolved discussions.

---

*[exists.go, line 28 \[r1\]](https://reviewable.io:443/reviews/mistifyio/gozfs/24#-KCH9C8Mfbt0iSZsLW-u:-KCHQ2DNLiPSm4VLDaOK:-499146009) ([raw file](https://github.com/mistifyio/gozfs/blob/79f4c96b37e939fb70b93b7f659f5d807bda9a7b/exists.go#L28)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/gozfs/24)*

**Comment by mmlb** [comment]
Reviewed 3 of 3 files at r2, 2 of 3 files at r3.
Review status: 16 of 17 files reviewed at latest revision, 6 unresolved discussions.

---

*[dataset.go, line 324 \[r1\]](https://reviewable.io:443/reviews/mistifyio/gozfs/24#-KCH4h8RycUVA3B6mAK6:-KCHPahJ5cc4NHo-edDO:-517188321) ([raw file](https://github.com/mistifyio/gozfs/blob/79f4c96b37e939fb70b93b7f659f5d807bda9a7b/dataset.go#L324)):*
clones. still exists on the second line ;)

---

*[dataset.go, line 364 \[r1\]](https://reviewable.io:443/reviews/mistifyio/gozfs/24#-KCH5Vnaj26MJ0FYCSn9:-KCHQ-E_IKBDFkKKxKWr:1463196066) ([raw file](https://github.com/mistifyio/gozfs/blob/79f4c96b37e939fb70b93b7f659f5d807bda9a7b/dataset.go#L364)):*
oh wait my mistake, by the time I got to here I thought `Dataset` was `type Dataset struct {
...
*ds
}`

Thoughts on having `Dataset.Properties` == `map[string]interface{}` that we unmarshal to?

---

*[dataset.go, line 500 \[r3\]](https://reviewable.io:443/reviews/mistifyio/gozfs/24#-KCHQlcxBGFpBWMFyAj5:-KCHQlcyH4Xp6KVMGzNn:-2107334544) ([raw file](https://github.com/mistifyio/gozfs/blob/02e65f386c8858a7813f0d8dcb6c24d31a430d10/dataset.go#L500)):*
Pool returns the zfs pool the dataset belongs to.

---

*[cmd/gozfs/main.go, line 1 \[r1\]](https://reviewable.io:443/reviews/mistifyio/gozfs/24#-KCH9bT1ncmWFT-Rr68Z:-KCHPiHgeez8OXDsYMmo:-491054771) ([raw file](https://github.com/mistifyio/gozfs/blob/79f4c96b37e939fb70b93b7f659f5d807bda9a7b/cmd/gozfs/main.go#L1)):*
I mean I did read it and it looks good, but I didn't spend too much brain time on it.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/gozfs/24)*

**Comment by TauZero** [comment]
Review status: 16 of 17 files reviewed at latest revision, 6 unresolved discussions.

---

*[dataset.go, line 176 \[r1\]](https://reviewable.io:443/reviews/mistifyio/gozfs/24#-KCH3Wqd23TqbACtGwvh:-KCHI_wYL7z3KAR960ok:-661353847) ([raw file](https://github.com/mistifyio/gozfs/blob/79f4c96b37e939fb70b93b7f659f5d807bda9a7b/dataset.go#L176)):*
because `ds` is the name of a type and worried about shadowing. Though I think it might have been shadowed elsewhere that could use fixing...

---

*[dataset.go, line 324 \[r1\]](https://reviewable.io:443/reviews/mistifyio/gozfs/24#-KCH4h8RycUVA3B6mAK6:-KCHUp9UMqm7pB9RFBgu:-499146009) ([raw file](https://github.com/mistifyio/gozfs/blob/79f4c96b37e939fb70b93b7f659f5d807bda9a7b/dataset.go#L324)):*
Done.

---

*[dataset.go, line 364 \[r1\]](https://reviewable.io:443/reviews/mistifyio/gozfs/24#-KCH5Vnaj26MJ0FYCSn9:-KCHSPTdwrUHXqibfeK6:-1550670136) ([raw file](https://github.com/mistifyio/gozfs/blob/79f4c96b37e939fb70b93b7f659f5d807bda9a7b/dataset.go#L364)):*
The property "values" are structures that vary (i.e. the set of `prop*` types). That would be shoving a lot of repetitive work onto the caller to just get at the real value. If we're going to give direct access, it might be easier to just make the whole `type ds` and related public.

---

*[dataset.go, line 500 \[r3\]](https://reviewable.io:443/reviews/mistifyio/gozfs/24#-KCHQlcxBGFpBWMFyAj5:-KCHUXDDbAwdFykwMT_2:-499146009) ([raw file](https://github.com/mistifyio/gozfs/blob/02e65f386c8858a7813f0d8dcb6c24d31a430d10/dataset.go#L500)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/gozfs/24)*

**Comment by mmlb** [comment]
Reviewed 1 of 3 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[dataset.go, line 176 \[r1\]](https://reviewable.io:443/reviews/mistifyio/gozfs/24#-KCH3Wqd23TqbACtGwvh:-KCHUwceOLUh-iiNHaOA:-121279786) ([raw file](https://github.com/mistifyio/gozfs/blob/79f4c96b37e939fb70b93b7f659f5d807bda9a7b/dataset.go#L176)):*
shadowing is really only a problem when shadowing other variables, in this case you'd be shadowing a type name, which the only problem would be that you could not instantiated a new variable of said type (which is not a problem here). Seems that it'll read better to refer to `ds.DMUObjsetStats` and co vs `in.DMUObjsetStats`

---

*[dataset.go, line 364 \[r1\]](https://reviewable.io:443/reviews/mistifyio/gozfs/24#-KCH5Vnaj26MJ0FYCSn9:-KCHVQLCU-Yxil0-cyeD:1678801607) ([raw file](https://github.com/mistifyio/gozfs/blob/79f4c96b37e939fb70b93b7f659f5d807bda9a7b/dataset.go#L364)):*
hmm agree on the pita due to types. I'm about 55% ok with making ds public.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/gozfs/24)*

**Comment by TauZero** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[dataset.go, line 465 \[r1\]](https://reviewable.io:443/reviews/mistifyio/gozfs/24#-KCH7dKZZyfrnTAEAnOO:-KCHWMfp0AJvmykdsFFn:1271105864) ([raw file](https://github.com/mistifyio/gozfs/blob/79f4c96b37e939fb70b93b7f659f5d807bda9a7b/dataset.go#L465)):*
The close here was to prevent the `<-done` from hanging. When `output` is not a `fdCloser`, we create a pipe, copying the reader end to the `output` with `io.Copy` in a goroutine and giving the writer end to the `send` command, and waits on a `done` chan. When the copy finishes, it sticks something on the done chan and the main `Send` can return. I think on success, there were a time where the EOF wasn't being written, so the `io.Copy` would hang and we'd be stuck. It seems that is no longer the case; I completely removed the `outputFdCloser.Close()`, leaving the `defer`ed pipe end closes, and it seems to work fine.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/gozfs/24)*

**Comment by TauZero** [comment]
Review status: 16 of 17 files reviewed at latest revision, 4 unresolved discussions.

---

*[dataset.go, line 176 \[r1\]](https://reviewable.io:443/reviews/mistifyio/gozfs/24#-KCH3Wqd23TqbACtGwvh:-KCHYN-Ne0YmyLCx9Ts2:1183581395) ([raw file](https://github.com/mistifyio/gozfs/blob/79f4c96b37e939fb70b93b7f659f5d807bda9a7b/dataset.go#L176)):*
Fair enough. Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/gozfs/24)*

**Comment by mmlb** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/gozfs/24)*

**Comment by TauZero** [comment]
Review status: 15 of 17 files reviewed at latest revision, 2 unresolved discussions.

---

*[dataset.go, line 364 \[r1\]](https://reviewable.io:443/reviews/mistifyio/gozfs/24#-KCH5Vnaj26MJ0FYCSn9:-KCI7QGdd5cm639kcvmt:1211819406) ([raw file](https://github.com/mistifyio/gozfs/blob/79f4c96b37e939fb70b93b7f659f5d807bda9a7b/dataset.go#L364)):*
After side discussion with manny, decided to make properties public in the Dataset.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/gozfs/24)*

**Comment by mmlb** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[dataset.go, line 29 \[r6\]](https://reviewable.io:443/reviews/mistifyio/gozfs/24#-KCI9vr9rG_5RVocq7xF:-KCI9vr9rG_5RVocq7xG:-1325413781) ([raw file](https://github.com/mistifyio/gozfs/blob/3ca1908fc5eccb853b98b7897dfefc56a75bb617/dataset.go#L29)):*
should add some info expanding on the `// Value manipulated` since that shows up in go doc.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/gozfs/24)*

**Comment by TauZero** [comment]
Review status: 16 of 17 files reviewed at latest revision, 1 unresolved discussion.

---

*[dataset.go, line 29 \[r6\]](https://reviewable.io:443/reviews/mistifyio/gozfs/24#-KCI9vr9rG_5RVocq7xF:-KCICA_ZxppOaXXY2h74:-499146009) ([raw file](https://github.com/mistifyio/gozfs/blob/3ca1908fc5eccb853b98b7897dfefc56a75bb617/dataset.go#L29)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/gozfs/24)*

**Comment by mmlb** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/gozfs/24)*

**Pull request merged**
